sys/dev/netmap/netmap.c, sys/dev/netmap/netmap_kern.h, sys/net/netmap.h, sys/net/netmap_user.h
In current modes (`NR_REG_ONE_NIC`, `NR_REG_ALL_NIC`) Netmap takes over all RX queues.
For some applications this is undesirable: the user might want to enable Netmap only on a single RX queue and leave the rest untouched (i.e. all packets flowing to other queues are handled as usual: pushed to the kernel without any Netmap interference).
This patch introduces support for a new mode called single RX queue (`NR_REG_SINGLE_RX`), in which an adapter exposes only the requested RX rings to the Netmap applications.
All the other RX queues are kept attached to the host stack, thus keeping all the network flows working as usual. The TX side is as well managed by the kernel, untouched by Netmap.
This mode can be useful for applications receiving packets at high speed, when it's not affordable to …
=> NR_REG_SINGLE_RX: single RX queue mode support

LINUX/configure
Linux Configure script has a typo in the help text.
"destir" should be "destdir"
=> Fix typo in Linux Configure Script

LINUX/configure, LINUX/dkms/dkms.conf
Since eb2e5621c065d6b they are not built from LINUX/ anymore
=> dkms: fix modules path

apps/pkt-gen/pkt-gen.c
In the expected context the use of htons is more appropriate. htons and
ntohs are actually implemented using the same function on x86, so there
is no actual functional problem.
=> Use htons to initialize packet's ip_len

sys/dev/netmap/netmap.c
The error exit path should reverse all operations in backward order of
the normal path. Till this commit if netmap_mem_if_new fails then
netmap_krings_put won't be called and the usage count will leak.
=> netmap_do_regif: Reverse error path vs normal path

LINUX/i40e_netmap_linux.h
For Ethernet frames of size larger than 2048 bytes, the ring for this driver always gives buffers of 2048 bytes or smaller chunks, even if the MTU is configured for > 9000 bytes, but it exposes a flag to inform the driver that more fragments are available for this frame.
This patch propagates the "more fragment" flag, from the NIC ring to the Netmap ring.
A similar check is done [in the mainline Linux i40e driver](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/drivers/net/ethernet/intel/i40e/i40e_txrx.c?h=v4.11.7#n1727).
Without this fix, when a 9014 byte frame is captured on the interface, a Netmap reader would receive 5 chunks of sizes : 2048 + 2048 + 2048 + 2048 +  822, without a way to tell if they belong to the same frame or not.
I have tested the change …
=> i40e: Set NS_MOREFRAG slot flag if frame is incomplete

sys/dev/netmap/netmap.c
The redefinition of ifp variable in the registration path was shadowing
a definition of the same variable at the start of netmap_ioctl function
and in case of netmap_do_regif failure the error path was trying to
unref the outer variable which contains NULL, while the ifnet object was
pointed by the inner ifp variable and as it went out of scope the ifnet
object will have one extra reference.
=> netmap_ioctl: Fix ifnet reference leak on failure.

apps/nmreplay/nmreplay.c
"-i" is only accepted a single time and the "-f" flag to provide
a pcap file wasn't given at all in the usage output.
=> Updates nmreplay usage display to match functionality.

.travis.yml, ci/build-linux
This adds integration with [Travis CI](https://travis-ci.org/) continuous integration service (free for open source projects).
For now the job (triggered automatically for each commit), will compile Netmap on Linux with all drivers, with several long term kernel versions and i386/x86_64 CPU architectures.
Basically it checks Netmap and its drivers compiles fines on Linux with a large range of kernel configurations, which can be very tedious to check manually. 
As an immediate benefit, it shows that Netmap is broken with the latest kernel version (Linus branch) : https://travis-ci.org/desbma/netmap/jobs/253780111#L957.
In the future we could expand the scope of the job to run automated tests, for example by firing up Qemu with a simulated e1000 NIC and exchanging some packets.
If you agree …
=> Add Travis CI integration

sys/dev/netmap/netmap_generic.c
The generic support in netmap send the packets using if_transmit() and the
loopback do not support packets coming from if_transmit()/if_start().
This avoids the use of the loopback interface and the subsequent crash that
happens when the application send packets to the loopback interface.
Details in:	https://github.com/luigirizzo/netmap/issues/322
Obtained from:	FreeBSD
=> Do not allow the use of the loopback interface in netmap.

LINUX/README
Problem statement
==============
patch final-patches/vanilla--e1000--20620--31200 is getting wrongly applied with 3.10 kernel version that is used for CentOS 7.3
Overview of changes
================
Updated the LINUX/README,  "COMMON PROBLEMS" section to alert the user of e1000 with netmap about the patch.
=> Updated the README about e1000 patch issue seen in 3.10 kernel version

apps/include/ctrs.h, apps/pkt-gen/pkt-gen.c
- Add a -N option to not normalize units.  Useful for automated tools.
(From olivier@ here:
https://github.com/ocochard/BSDRP/tree/master/BSDRPcur/patches)
- Or in -o option so command-line order of -I, -X, -r, -z, -Z, and -A
doesn't matter.
- Avoid unaligned access, some new compilers will warn on it, and pkt-gen
uses -Werror -Wall.
- Document all supported options in usage() (even -m).
- Remove documentation of unsupported -r and -t options
- Align tabs in usage()
=> Various pkt-gen fixes

LINUX/i40e_netmap_linux.h
Replace the check whether interface is running with a check whether
there is actual carrier, otherwise packets will be reported as sent
although there is no actual link on the interface.
Tested by sending packets with:
```
pkt-gen -i ethX -f tx -n 0 -l 1500
```
Pkt-gen shows that it is sending packets even after the cable was
physically unplugged from the interface.
The check in ixgbe is the same in txsync handler.
=> Check if carrier present instead of running.

sys/dev/netmap/netmap_mem2.c
The error: 'struct lut_entry' has no member named 'paddr'
=> Fixed lut_entry has no paddr member issue

sys/dev/netmap/netmap_mem2.c
One some platforms this previously resulted in
nr_buf_size being initialised to random values
as only 16-bits of the 32 bit value was set.
The symtoms were that buffer offsets were
incorrectly calculated and invalid memory
accesses occurred.
=> mem: fix non-const casting of nr_buf_size

LINUX/if_igb_netmap.h, sys/dev/netmap/netmap_kern.h
Syncing of DMA maps now works for TX path also. Integrated and tested for IGB, as I have NICs using this driver only.
Relates to issue #409.
=> Sync dma for tx path

LINUX/README
Document that promiscuous mode may need to be turned on after starting
the netmap application. This may require temporarily turning off the
mode.
=> linux: promiscuous mode improvements to LINUX/README

share/man/man4/netmap.4, sys/dev/netmap/netmap.c, sys/dev/netmap/netmap_kern.h, sys/dev/netmap/netmap_pipe.c, sys/dev/netmap/netmap_vale.c, utils/testmod/kern_test.c
There are some efforts in FreeBSD to decrease the number of sysctls with missing descriptions. This patch adds simple descriptions to all of those without them. I figure it is better to make the change here rather than in the FreeBSD source. Additionally, I found there were a couple of sysctls missing from the netmap man page, so I added those as well. Since I am unfamiliar with the netmap source I would appreciate any corrections needed for my descriptions.
=> Add descriptions to undocumented sysctls

apps/dedup/dedup.h
My build on CentOS 7.4 failed with the error
```
make[1]: Entering directory `/build/netmap-sl74/build-apps/dedup'
cc -O2 -pipe -g -Werror -Wall -Wunused-function -I /build/netmap-sl74/LINUX/../sys -I /build/netmap-sl74/LINUX/../apps/include -Wextra   -c -o dedup.o /build/netmap-sl74/LINUX/../apps/dedup/dedup.c
In file included from /build/netmap-sl74/LINUX/../apps/dedup/dedup.c:6:0:
/build/netmap-sl74/LINUX/../apps/dedup/dedup.h:4:0: error: "_BSD_SOURCE" redefined [-Werror]
#define _BSD_SOURCE
^
In file included from /usr/include/stdio.h:27:0,
from /build/netmap-sl74/LINUX/../apps/dedup/dedup.c:1:
/usr/include/features.h:188:0: note: this is the location of the previous definition
^
cc1: all warnings being treated as errors
make[1]: *** [dedup.o] Error 1
make[1]: Leaving directory …
```
=> _BSD_SOURCE is already defined in /usr/include/features.h (CentOS 7.4)

LINUX/configure, LINUX/final-patches/mellanox--mlx5--3.3, LINUX/mlx5_netmap_linux.h
Hi,
As previously discussed, please find attached patches for the Mellanox mlx5 Ethernet driver for use with ConnectX-4 and ConnectX-5 cards (Resolves #210).
As we build things a little differently internally I've refactored our internal code to suit the netmap codebase, following the same sort of method used to pull in external Intel drivers for patching (as opposed to patching the kernel source).
Whilst I am able to build this, I haven't yet tackled the necessary changes to LINUX/default-config.mak.in_ to enable downloading and patching of the relevant tarball. I'm hoping the details below will help with this, and I'm happy to make further changes as required to make it fit in.
Build process:
* Download tgz from http://www.mellanox.com/downloads/Drivers/mlnx-en-3.3-1.0.0.0.tgz
* Unpack, …
=> Add support for Mellanox ConnectX-4 / ConnectX-5 cards (v3.3 mlx5 driver)

LINUX/netmap_linux.c, WINDOWS/netmap_windows.c, sys/dev/netmap/netmap.c, sys/dev/netmap/netmap_freebsd.c, sys/dev/netmap/netmap_kern.h
The following patch adds support for checksum offloading to hardware when using the emulated driver function of netmap. In our use case where netmap originates traffic (rather than the main use case of forwarding) it's useful to have this mode available as a fallback.
There's a sysctl parameter added to enable this function, which remains disabled by default.
Assuming this looks generally acceptable as a contribution, I'd appreciate a review, not least in the following two areas:
* The first commit changes where the mbuf protocol is identified from (using the location of the ethertype rather than assuming IPv4)
* The second commit disables the offloading check in netmap.c when the new sysctl parameter is enabled. This is necessary to allow CHECKSUM_PARTIAL cases to pass, but also removed …
=> Add checksum offload capability for emulated driver

apps/pkt-gen/pkt-gen.c
See: https://github.com/luigirizzo/netmap/issues/499
=> pkt-gen: Use first_tx_ring instead of 0 (needed for host rings)

sys/dev/netmap/netmap_mem2.c
Variable was not declared and log statement caused error.
=> change variable name to fix bug

sys/dev/netmap/netmap_freebsd.c
See FreeBSD PR206053 (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=206053) for details.
=> Fix FreeBSD PR206053 - panic when adding netmap device to kqueue.

share/man/man4/netmap.4
Looks like old docs says that kqueue is unsupported.  Multiple other places in the page says that it is supported.
=> remove docs about how kqueue is unsupported

sys/dev/netmap/netmap_mem2.c
memset is based on number of bytes not the sizeof(u32). therefore, not all bitmap bytes initialized
=> netmap/netmap_mem2: fix memory pool bitmap not initialized all bits

sys/dev/netmap/netmap_vale.c
If netmap_vale_attach() is called with a memory region, it
will leak a reference to that region.  Make sure to do a
netmap_mem_put in this case. 
Fixes issue 559
=> netmap_vale_attach can leak memory references

apps/nmreplay/nmreplay.8, apps/nmreplay/nmreplay.c
The help message in nmreplay is misleading. nmreplay will not work if you only put the interface name. It has to be preferenced with netmap: in order to work. However, if it fails you are simply told "could not open interface <interface>" which leaves the user thinking there is another problem.
=> Update help message in nmreplay

LINUX/default-config.mak.in_, LINUX/final-patches/mellanox--mlx5--4.5, LINUX/mlx5_netmap_linux.h
This PR adapts the patch for Mellanox 3.3 tested on ConnectX-4, to the 4.5 driver tested with ConnectX-5.
I would like to get some feedback before I do this and squash the commits together.
I left a couple of TODOs, especially in places where we have to check if a queue is using netmap or not.
Note: it is not possible to select 3.3 or 4.5, because the source tarballs have different format (in both cases it's a tgz inside a tgz inside a tgz ..........)
Comments welcome!
=> Mellanox 4.5 ConnectX-5

LINUX/netmap_linux.c, sys/dev/netmap/netmap.c, sys/dev/netmap/netmap_kern.h
If the linux interface device driver supports NS_MOREFRAG or the
new MTU still fits within a netmap buffer, allow the MTU to be
changed.
=> Add ability to change MTU once device driver is loaded.

LINUX/final-patches/mellanox--mlx5--4.5
The way the MLX5 Makefile for driver version 4.5 is patched generates "undefined symbol" errors when using a driver-suffix, resulting in an unusable driver. I have corrected the patch so the driver-suffix is handled properly.
=> MLX5 driver unusable when specifying a driver-suffix

libnetmap/nmport.c
nmport_mmap doesn't correctly initialize num_rx before using it to determine first_rx_ring
=> Make sure num_rx is correctly initialized

extra/python/netmap_manager.c, share/man/man4/netmap.4, sys/dev/netmap/netmap_mem2.c, sys/net/netmap_legacy.h, sys/net/netmap_user.h, utils/ctrl-api-test.c, utils/testmmap.c
In testing, when using buf_num over 420,000 or so, with the default
clusternumbers, we run into integer overflow and segfault. 
In our environment, we have 40 core servers (20+20) with the nics using
40 tx/rx rings, with the ring slot size set to 4096. We have to set the
buf_num to about 750000 in order to allocate enough memory for our
application to load with around 100000 extra buffers.
This segfaults without this change.
This is basically adapted from issue #602. I left the max buffers at the
default of 1_000_000 and changed some %lu and %ld to %zu %zd
=> Use size_t instead of u_int for total memory.

LINUX/final-patches/mellanox--mlx5--4.6
This PR updates the existing patches for the Mellanox Ethernet driver to v4.6.
=> Update mlx5 driver to v4.6

LINUX/netmap_linux.c
VmRSS     size of memory portions. It contains the three
following parts (VmRSS = RssAnon + RssFile + RssShmem)
RssAnon   size of resident anonymous memory
RssFile   size of resident file mappings
RssShmem  size of resident shmem memory (includes SysV shm,
mapping of tmpfs and shared anonymous mappings)
The kernel differentiates between RssFile and RssShmem by
checking the PG_swapbacked flag on the page. By setting this
flag the netmp memory will be recorded as RssShmem.
=> Record mapped netmap memory as RssShmem rather than RssFile

LINUX/veth_netmap.h
Remove peer in veth_netmap_krings_delete(vna) because without that
subsequent call of veth_netmap_krings_create(vna->peer) do not create rings.
=> veth: fix segfault at access to not created adapter rings

LINUX/bsd_glue.h, LINUX/configure
As of Linux v5.6 struct timeval does not exist (in the kernel). Detect
this and define our own when needed.
Fixes #689
Signed-off-by: Chris Packham <chris.packham@alliedtelesis.co.nz>
=> linux/configure: check for struct timeval

libnetmap/libnetmap.h, sys/net/netmap_user.h
@giuseppelettieri I fixed the macro from https://github.com/luigirizzo/netmap/commit/a2b1b4ea221a63626ff4b1bfa07c6c356da28434#commitcomment-39365274
I also found a few typos in libnetmap.h, I hope that you dont mind
Note that I didn't actually test the offset support. I'm just experimenting with some of the netmap features. I'm using i40e and it looks like offset is just implemented in e1000
=> fix NETMAP_WOFFSET and typos

sys/dev/netmap/netmap_legacy.c
Code was checking for NETMAP_{SW,HW}_RING in req->nr_ringid which
had already been masked by NETMAP_RING_MASK. Therefore, the comparisons
always failed and set NR_REG_ALL_NIC. Check against the original nmr
structure.
=> fix parsing of legacy nmr->nr_ringid

LINUX/bsd_glue.h
GFP_ATOMIC prevents memory reclaim. In the scenario where the device
has been running for a while the number of free pages can be low,
but the file cache can be large. Without allowing memory reclaim
we would get "page allocation failures".
https://github.com/luigirizzo/netmap/issues/673
=> linux: Use GFP_USER for contiguous memory allocation

LINUX/configure, LINUX/default-config.mak.in_, LINUX/final-patches/mellanox--mlx5--5.0
~- I need to remove txsync from the header and put it in the second header and have it build. They have separated tx and rx code so you can't just include a header with both functions any more~
=> mlx5 5.0 patch

apps/pkt-gen/pkt-gen.8, apps/pkt-gen/pkt-gen.c
In addition to the corrections in this request, there appear to be options not described in the man page. For example the `-o options` field is listed in the `usage()` function but not described in the man page.
=> pkt-gen: minor corrections to documentation

share/man/man4/netmap.4, sys/net/netmap_user.h
Compiler generates some warnings when `-Wcast-qual` option is used and `netmap_user.h` is included in a program. This pull request fixes the problematic code.
It also fixes a simple error in the example code presented in `netmap(4)`.
=> Fix constness warnings generated when "-Wcast-qual" compiler option is used.

sys/dev/netmap/netmap_mem2.c
Hello,
I am testing FreeBSD-12.2-RC3 using a kernel with INVARIANTS enabled. I was starting pkt-gen on an interface with a large number of rings and had forgotten to increase the if_size sysctl. A memory allocation failed and the system hit a panic.
Panic message:
```
Lock (&nm_mem)->nm_mtx not exclusively locked @ /usr/src/sys/dev/netmap/netmap_mem2.c:271
```
=> freebsd: fix mutex double unlock

LINUX/netmap_linux.c, sys/dev/netmap/netmap_generic.c
Wrong headroom calculations lead to pskb_expand_head() in the drivers.
It fails since skb is shared. Correct calculations prevent
expanding skb.
=> Fix BUG_ON() in Linux on vxlan/gretap/hyper-v interfaces

apps/pkt-gen/GNUmakefile
All the other apps append to the `LDFLAGS` variable, but not the `pkt-gen` application. Without this, it is impossible to use the environment variable to configure this variable.
=> Append to ldflags instead of assignation

LINUX/netmap_linux.c, WINDOWS/win_glue.h, sys/dev/netmap/netmap.c, sys/dev/netmap/netmap_kern.h, sys/dev/netmap/netmap_mem2.c, sys/dev/netmap/netmap_mem2.h
mem: create allocator for each iommu group (on demand)
Assign allocator iommu group id (nm_grp) at initialization stage and do not change it later.
Check group only for hw (hardware) adapters. Virtual adapters can use any
particular allocator. For example, we can choose vale allocator through vale-ctl -m
nm_iommu_group_id() return -1 on error instead of 0, because 0 is valid iommu group.
issue: https://github.com/luigirizzo/netmap/issues/688
=> Enable netmap to run on several interfaces from different iommu groups

LINUX/final-patches/mellanox--mlx5--5.0
This fixes #764, but only for driver version 5.0.
The problem was that mlx5e_modify_rq_state() reset the work queue which messed up synchronization between the mlx5 work queue and netmap ring if it was done after mlx5e_netmap_configure_rx_ring() was already called.
=> mlx5: call mlx5e_netmap_configure_rx_ring() *after* resetting wq

LINUX/final-patches/mellanox--mlx5--5.1
Full commit hash f14770c7f84985fccd7a3f28b5ccf167f38ac587
@driesdewinter Do you want to be set as the author of this patch since it is your fix?
=> mlx5: copy fix for RX packet loss from f14770c7 into 5.1

sys/net/netmap.h
Compiling the following C++ program on FreeBSD (11.4 / 12.1) currently fails.
This affects the netmap plugin for Zeek [1].
$ cat test_netmap.cc
#include <iostream>
extern "C" {
#define NETMAP_WITH_LIBS
#include <net/netmap_user.h>
}
int main(int argc, char *argv[])
{
std::cout << "netmap" << std::endl;
}
$ clang++  ./test_netmap.cc
In file included from ./test_netmap.cc:5:
In file included from /usr/include/net/netmap_user.h:100:
In file included from /usr/include/net/netmap.h:814:
/usr/include/stdatomic.h:187:17: error: unknown type name '_Bool'
typedef _Atomic(_Bool)                  atomic_bool;
^
/usr/include/stdatomic.h:187:26: error: C++ requires a type specifier for all declarations
typedef _Atomic(_Bool)                  atomic_bool;
Similar issues [2,3] (though GCC) suggest to …
=> netmap.h/freebsd: Include <atomic> instead of <stdatomic.h> when compiling with C++

LINUX/configure, LINUX/default-config.mak.in_, LINUX/if_stmmac_netmap_linux.h, apps/pkt-gen/pkt-gen.c, libnetmap/nmctx.c, libnetmap/nmport.c, sys/dev/netmap/netmap_mem2.c
1. add stmmac netmap support (linux version), and
2. fix compiler warning when cross building the driver with:
arm-buildroot-linux-gnueabihf-gcc (Buildroot 2019.02.2-g0b3ebc6ca5-dirty) 8.3.0
=> stmmac: add stmmac port

apps/tlem/tlem.c, sys/net/netmap_user.h, utils/testmmap.c
This fixes those 32/64-bit type mismatch errors when compiling on the Pi.
=> fix compilation on Raspberry Pi

LINUX/bsd_glue.h, LINUX/configure
https://patchwork.kernel.org/project/linux-mm/patch/20210430055556.xcmsU3Fo2%25akpm@linux-foundation.org/
=> linux: FOLL_SPLIT is removed in 5.15.

LINUX/default-config.mak.in_
Similar to closed issue #816 but this time errors occurred when running make install.
=> Fixes ERROR: modpost errors when running make install on Debian Bullseye

apps/nmreplay/nmreplay.c
Fix compilation and correct usage of the err variable:
nmreplay.c:1105:13: error: variable 'err' set but not used [-Werror,-Wunused-but-set-variable]
int ch, i, err=0;
=> Fix variable 'err' usage and compilation

LINUX/veth_netmap.h
Check peer_ref before incrementing/decrementig na_refcount.
Oops can be reproduced with pkt-gen:
ip l a dev vetha type veth peer name vethb
./build-apps/pkt-gen/pkt-gen -f rx -i vetha &
sleep 1
./build-apps/pkt-gen/pkt-gen -f rx -i vethb^ &
sleep 1
./build-apps/pkt-gen/pkt-gen -f rx -i vethb-0 &
sleep 1
killall pkt-gen
./build-apps/pkt-gen/pkt-gen -f rx -i vetha
There is two calls of nm_register for interface vethb.
First one on creating host-ring vethb^ and the second on vethb-0.
If we do not check peer_ref then we would dereferencing peer twice.
=> linux/veth: fix kernel oops

apps/pkt-gen/pkt-gen.c
The current ```pkt-gen``` tool only flips the source and destination MAC address without flipping the IP addresses. This becomes problematic when working with links with NAT or hops in between. The PR flips the IPv4 address in a pong response.
=> Swap the src and dst IPv4 address in the pong msg

apps/lb/pkt_hash.c
As far as I can tell the missing `ntohs()` can lead to the hash being erroneously set to zero, which could break load balancing.
=> lb/pkt_hash: Fix ip_hl check.

apps/lb/pkt_hash.c
This member of the IPv6 header is only 1 byte and therefore should not be byte-swapped using ntohs.  Using ntohs on this value means that none of the cases in the switch statement will match and the default case will always be chosen.
In addition, the correct ICMP definition for IPv6 should be IPPROTO_ICMPV6 instead of IPPROTO_ICMP.
=> fix ipv6h->ip6_ctlun.ip6_un1.ip6_un1_nxt usage

apps/pkt-gen/pkt-gen.c
While testing with pkt-gen on FreeBSD-12.3, I observed that the source MAC address was always 00:00:00:00:00:00. I looked at the code and saw that `source_hwaddr()` should retrieve the system interface MAC address and set it as the source.
After some debugging, I discovered that the argument parsing code in `main()` was prefixing the interface with "netmap:" if no type was given. (At the same time, it removed any "tap:" or "pcap:" prefixes.) Therefore, when it came time to compare the interface name to the system interfaces, there was never a match for netmap devices.
My proposed fix is to check if the interface begins with "netmap:" in `source_hwaddr()` and if so, skip over that prefix. In my testing, the fix correctly obtains the hardware MAC address and uses it as the source MAC.
=> pkt-gen.c: fix ifname before comparing in source_hwaddr()

apps/pkt-gen/pkt-gen.c
Hello,
I observed sporadic rx-err packets when using pkt-gen between two FreeBSD systems. Sporadic meaning it didn't happen every run but if it did happen it continued every second. Using the OPT_DUMP option to log all outgoing packets, I saw there was one packet each burst that was all zeros.
Some code reading brought me to the "drop copy" log message. sender_body() adds OPT_COPY to the options which forces a copy of the packet data into the ring slot. After 100,000 packets the function removes the OPT_COPY option. I suspect the reasoning was by that point every slot has a copy of the packet and there is a significant performance improvement by not copying the packet every time.
The problem occurs with multiple transmit rings. The code always starts with the first ring and moves on if a …
=> pkt-gen: fix sending uninitialized slots when using multiple tx rings

apps/pkt-gen/pkt-gen.c
The type of `tv_sec` is `time_t`, which is 32-bit on some platforms. The type of `tv_nsec` is `long` (`long long` only since C23).
When building the port net/pkt-gen without this patch, a package fallout occurs.
Cast to an `intmax_t` to avoid the warning/error, given `-Werror` (NB: The original patch in the net/pkt-gen port used a `long long`, we opted for an `intmax_t` instead).
See the aftermath of bug report #270440 for further details.
=> Fix compilation on some 32-bit platforms

apps/pkt-gen/pkt-gen.c
Hello,
pkt-gen can randomize the packet length using -l maxsize -l minsize arguments. It creates the initial packet using the maximum size, sets the length in the headers, and computes the checksums. Then for each burst it gets a random length and simply truncates the packets to that length.
The result is the IP total length is incorrect as well as the UDP length and checksum (since it is computed over the payload). I have not observed any data sinks that could not handle these inconsistencies, but as a test tool I would like pkt-gen to create valid packets.
I have written a patch that updates the IP/UDP lengths after the new burst size is determined. Then for UDP it recalculates the checksum by walking the new payload. (I considered trying a delta calculation based on the old and new …
=> pkt-gen: update IP length, UDP length/checksum when size changes

apps/pkt-gen/pkt-gen.c
=> pkt-gen: Silence an unused parameter warning

LINUX/bsd_glue.h, LINUX/netmap_linux.c
Define being generated in LINUX/configure was slightly different to what was being used in code.
=> linux: Use correct define for vlan untagging.

libnetmap/nmreq.c
When trying to use a VLAN device (e.g. "em0.123") with a dot
the library fails to parse the interface correctly. The former
pattern is much too restrictive given that almost all characters
can be coerced into a device name via ifconfig.
Remove the particularly restrictive validation.  Some characters
still cannot be used as an interface name as they are used as
delimiters in the syntax, but this allows to be able to use most
of them without an issue.
Note that the dotted VLAN naming is the default in FreeBSD now
and a patch was proposed here https://reviews.freebsd.org/D42485
as well.
=> libnetmap: remove interface name validation

LINUX/configure, LINUX/netmap_linux.c
In older kernels net_if_rx() is to be used in interrupt context and netmap nm_os_send_up() is from process context. Thus using netif_rx_ni() is correct function variant in this case and using it prevents pending softirqs. In newer kernels netif_rx() can handle both contexts.
=> linux: use net_if_rx_ni() in nm_os_send_up()

LINUX/netmap_linux.c
Hello,
I believe this patch is a fix for issue #937 where fortify causes a panic in `tc_configure()` due to a "detected buffer overflow in strcpy". The `nlattr *` is set to `&nlreq.hdr` which has a fixed size causing the overflow. By setting `nlattr *` to `&nlreq` instead, the code sees the 100 byte `buf` space and does not panic. I tested this on kernel 6.5.0-21 and verified the `qdisc` name was properly set by using `tc`. With the fix I could run `pkt-gen` on multiple emulated netmap interfaces without seeing a panic.
While here I removed a duplicate `strcpy()` in `netmap_sink_init()`. I assumed "nmsink" is preferred to "nmsink%d".
=> Fix Linux 6.5 support to avoid fortify panic

LINUX/default-config.mak.in_, LINUX/dkms/dkms.conf, LINUX/final-patches/mellanox--mlx5--5.3, LINUX/final-patches/mellanox--mlx5--5.8, LINUX/mlx5_netmap_linux.h
* An old bugfix was missed in driver version 5.3.  I've had this patch for 2 years and I think I tested it at the time but we have moved past that version.
* I discovered that mellanox/nvidia provide a smaller tarball we can download to build netmap that does not bundle large debs.  This smaller tarball has the same sha256sum as the first inner tarball of the larger one.
* We are starting to test driver version 5.8 but early tests show no obvious problems with TX or RX.  If others want to test it please do.
* We use dkms to package but never shared the "recipe".
=> Some mellanox housekeeping and a new driver version

sys/dev/netmap/netmap.c, utils/ctrl-api-test.c
If the allocation falls on a larger slab, such as 8K (which was the case with this allocation due to bufsz), we can safely overwrite the memory. However, with KASAN (Kernel Address Sanitizer) enabled, I could see out-of-bound access. This patch should resolves that issue.
=> generic: fix possible out of bound write
